config/routes.rb
Rails.application.routes.draw do
  resources :playerencounters
  resources :encountermonsters
  resources :dungeonmasters
  resources :players
  resources :monsters
  resources :encounters do 
    member do
    get 'fight'
  end
end


  get '/encounters/:id/fight', to: 'encounter#edit', as: "encounter_fight"
  get '/welcome', to: 'login#new'
  post '/login', to: 'login#create'

  root "login#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dungeonmaster.rb
class Dungeonmaster < ApplicationRecord
    has_many :players
    has_many :encounters
    has_many :encountermonsters, through: :encounters
    has_many :monsters, through: :encountermonsters
    has_secure_password
    validates :username, uniqueness: true
    
end

app/controllers/dungeonmasters_controller.rb
class DungeonmastersController < ApplicationController


    def index
        @encounters = Encounter.all
        @dungeonmasters = Dungeonmaster.all
        #need to somehow have this associated with the instance of dm we're signed in as
    end
    
    def new
        @dungeonmaster = Dungeonmaster.new
    end

    def create
        @dungeonmaster = Dungeonmaster.create(dm_params)
        if @dungeonmaster.valid?
            flash[:message] = "Created #{@dungeonmaster.name}."
            redirect_to @dungeonmaster
        else 
            flash[:message] = "Ya dun goofed."
            redirect_to "/welcome"
        end
    end

    private

    def dm_params
        params.require(:dungeonmaster).permit(:name, :username, :password)
    end

end

app/helpers/dungeonmasters_helper.rb
module DungeonmastersHelper
end

app/views/dungeonmasters/_form_dm.erb
<h1>Create/Edit A DM</h1>

<%= form_for @dungeonmaster do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :password %>
<%= f.password_field :password %>


<div class="bigsubmit blindcenter">
<%= f.submit%>
</div>

<%end%>

app/views/dungeonmasters/edit.html.erb
<h1>DM Edit</h1>

<%= render 'form_dm'%>

app/views/dungeonmasters/index.html.erb
<h1>DM Index</h1>

<div>
<h1>Index of Encounters</h1>
    <% @encounters.each do |encounter|%>
    <li><%= link_to encounter.name, encounter_path %></li>
    <%end%>


</div>


<%= link_to "Create A Player", new_player_path%>
<%= link_to "Create An Encounter", new_encounter_path%>

app/views/dungeonmasters/new.html.erb
<h1>DM New</h1>

<%= render 'form_dm'%>

app/views/dungeonmasters/show.html.erb
<h1>DM Show</h1>

<div class="blindcenter group-paths">
<%= link_to "All Monsters", monsters_path %>
<%= link_to "All Players", players_path %>
<%= link_to "All Encounters", encounters_path %>

</div>