config/routes.rb
Rails.application.routes.draw do
  resources :playerencounters
  resources :encountermonsters
  resources :dungeonmasters
  resources :players
  resources :monsters
  resources :encounters do 
    member do
    get 'fight'
  end
end


  get '/encounters/:id/fight', to: 'encounter#edit', as: "encounter_fight"
  get '/welcome', to: 'login#new'
  post '/login', to: 'login#create'

  root "login#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/encounter.rb
class Encounter < ApplicationRecord
  belongs_to :dungeonmaster
  has_many :playerencounters, dependent: :destroy 
  has_many :players, through: :playerencounters
  has_many :encountermonsters, dependent: :destroy
  has_many :monsters, through: :encountermonsters
  
  validates :name, presence: true, uniqueness: true
  

  # xp per CR = Monster Manual pg 10
  # player xp threshold = DMG pg 82

  def get_target_cr

  end

  
  def get_monster_list(monster_count)
    if(monster_count > 0)
      xp_per_mob = calc_party_xp_threshold / monster_count
      xp_per_mob = xp_per_mob / monster_multiplier(monster_count)
      monster_cr = get_monster_cr(xp_per_mob)
      monster_list = Monster.find_by_cr(monster_cr)
    end
  end

  def get_monster_cr(xp_per_mob)
    case xp_per_mob
      when 0..24                      then 0.0
      when 25..49                     then 0.125
      when 50..99                     then 0.250
      when 100..199                    then 0.500
      when 200..449                    then 1.0
      when 450..699                    then 2.0
      when 700..1099                    then 3.0
      when 1100..1799                   then 4.0
      when 1800..2299                   then 5.0
      when 2300..2899                   then 6.0
      when 2900..3899                   then 7.0
      when 3900..4999                   then 8.0
      when 5000..5899                   then 9.0
      when 5900..7199                   then 10.0
      when 7200..8399                   then 11.0
      when 8400..9999                   then 12.0
      when 10000..11499                  then 13.0
      when 11500..12999                 then 14.0
      when 13000..14999                 then 15.0
      when 15000..17999                 then 16.0
      when 18000..19999                 then 17.0
      when 20000..21999                 then 18.0
      when 22000..24999                 then 19.0
      when 25000..32999                 then 20.0
      when 33000..40999                 then 21.0
      when 41000..59999                 then 22.0
      when 50000..61999                 then 23.0
      when 62000..74999                 then 24.0
      when 75000..89999                 then 25.0
      when 90000..104999                then 26.0
      when 105000..119999                then 27.0
      when 120000..134999                then 28.0
      when 135000..149999                then 29.0
      else  30.0
    end
  end


  def monster_multiplier(monster_count)

    case monster_count
      when 1                then 1.0
      when 2                then 1.5
      when 3..6             then 2.0
      when 7..10            then 2.5
      when 11..14           then 3.0
      when 15..100          then 4.0
    end

  end

  


  def calc_party_xp_threshold
    party_levels = self.players.pluck(:player_level)
    @party_xp_threshold = self.medium_cr_calculation(party_levels)
  end


  def hard_cr_calculation(party_levels)

  end


  def medium_cr_calculation(party_levels)
    
    @party_xp_total = 0
    party_levels.each do |level|
      case level
        when 1      then @party_xp_total+=50
        when 2      then @party_xp_total+=100
        when 3      then @party_xp_total+=150
        when 4      then @party_xp_total+=250
        when 5      then @party_xp_total+=500
        when 6      then @party_xp_total+=600
        when 7      then @party_xp_total+=750
        when 8      then @party_xp_total+=900
        when 9      then @party_xp_total+=1100
        when 10     then @party_xp_total+=1200
        when 11     then @party_xp_total+=1600
        when 12     then @party_xp_total+=2000
        when 13     then @party_xp_total+=2200
        when 14     then @party_xp_total+=2500
        when 15     then @party_xp_total+=2800
        when 16     then @party_xp_total+=3200
        when 17     then @party_xp_total+=3900
        when 18     then @party_xp_total+=4200
        when 19     then @party_xp_total+=4900
        when 20     then @party_xp_total+=5700
      end
    end

    return @party_xp_total
  end

  def easy_cr_calculation(party_levels)

  end



end

app/controllers/encounters_controller.rb
class EncountersController < ApplicationController
    before_action :find_encounter, only: [:show, :edit, :update, :destroy]


    def index 
        @encounters = Encounter.all
    end
    
    def new
        @encounter = Encounter.new()
        @players = Player.all()
        #DM is temp until we can pass ID on creation
        @dungeonmasters = Dungeonmaster.all()
    end

    def create
        if(!params[:encounter][:player_ids][1])
            flash[:error] = "No!"
            redirect_to new_encounter_path
        else
            @encounter = Encounter.create(encounter_params)
            if(@encounter.valid?)
                attach_players_to_encounter
                
                redirect_to edit_encounter_path(@encounter)
            else
                flash[:error]=@encounter.errors.full_messages
                redirect_to new_encounter_path
            end
        end


    end


    def update
        if(params[:monsters])
            params.permit(:monsters)
            params[:monsters].each do |mob_id|
                Encountermonster.create(encounter_id: @encounter.id, monster_id: mob_id)
            end
            
            redirect_to encounters_path
        else
            #flash[:error]=
            redirect_to edit_encounter_path(@encounter)
        end
    end

    def show

    end

    
    def edit
        @monster_list = @encounter.get_monster_list(@encounter.monster_quantity)
    end

    def destroy
        @encounter.destroy
        redirect_to encounters_path 
    end

    def fight
        find_encounter
    end


    private

    def find_encounter
        @encounter = Encounter.find(params[:id])
    end

    def encounter_params
        params.require(:encounter).permit(:dungeonmaster_id, :name, :monster_quantity, :terrain_type, :player_ids)
    end

    def attach_players_to_encounter
        params[:encounter][:player_ids].each do |char_id|
            if(char_id)
                Playerencounter.create(player_id: char_id, encounter_id: @encounter.id)
            end
        end
    end

end

app/helpers/encounters_helper.rb
module EncountersHelper
end

app/views/encounters/_form_encounters.erb
<% if(flash[:errors]) %>
    <ul>
        <% flash[:errors].each do |error| %>
            <li>
                <%= error %>
            </li>
        <%  end %>
    </ul>
<% end %>
<div class="blindcenter" >
    <%= form_for(@encounter) do |f| %>
        <div>
            <%= f.label :name %>
            <%= f.text_field :name %>
        </div>

        <div>
            <%= f.label :monster_quantity %>
            <%= f.select(:monster_quantity, (1..10))%>
        </div>
        
        <p>
            <%= f.label :player_ids %>
            <div>
                <%= f.collection_check_boxes(:player_ids, @players, :id, :name, :item_wrapper_class => 'checkbox_container') %>
            </div>
        </p>

        <div>
            For Testing:
            <%= f.label :dungeonmaster_id %>
            <%= f.collection_select(:dungeonmaster_id, @dungeonmasters, :id, :name) %>
        </div>
        


        <%= f.submit %>
    <%end%>

</div>

app/views/encounters/edit.html.erb
<h1>Edit Encounter</h1>

    <div>
        <h5>Current CR: TBA  </h5>
    </div>
    <div>
        <h5>Target Number of Monsters: <%= @encounter[:monster_quantity] %> </h5>
    </div>
    <div>
        <h5>Selected Monsters:</h5>
            <% if(@encounter.monsters) %>
                <ul>
                    <% @encounter.monsters.each do |monster| %>
                        <li>
                            <%= link_to monster.monster_name, monster %>
                        </li>
                    <% end %>
                </ul>
            <% end %>
    </div>

<p>

    <%= form_for(@encounter) do |f| %>
        <h5>Available Monsters:</h5>
        <div>
            <% @monster_list.each do |monster| %>
                <span><br><%= monster.monster_name %></span>
                <%= check_box_tag "monsters[]", monster.id %>  
            <% end %>
        </div>
        
        <%= f.submit "Select Monsters"%>
    <% end %>

</p>

app/views/encounters/fight.html.erb
<h1>Time to Fight: <%= @encounter.name %> </h1>

<div>
    <h3>Dungeon Master: <%= @encounter.dungeonmaster.name %></h3>
</div>
<div class="grid-container">
    <div class = "item1">
        <%= image_tag("phbcover.jpg", :size => "300x200") %>
        
        <p>
            <h4>Encounter tracker stuff goes here. </h4>
        </p>
        <p>
            <h4>Use your imagination. It's glorious!</h4>
        </p>    
        


    </div>
    <div class = "item3">
        <p>
            Players: <% @encounter.players.each do |player| %>
                <div class="flex-container3col">
                    <span class="flex-item"> <strong> Name: </strong> <%= player.name %>  </span>
                    
                        <span class="flex-item"> <strong> Level: </strong>  <%= player.player_level %>  </span>
                        <span class="flex-item"> <strong> HP:  </strong> <%= player.player_hp %> </span> 
                    
                </div>
            <% end %>
        </p>
        <p>
            Monsters: <% @encounter.encountermonsters.each do |encountermonster| %>
                <div class="flex-container3col"> 
                    
                    <span class="flex-item">Name: <%= encountermonster.monster.monster_name %> </span>
                    <span class="flex-item">CR: <%= encountermonster.monster.challenge_rating %></span>
                    
                </div>
            <% end %>
            
        </p>
        <p>
            <%= link_to "Return to Encounter Index", encounters_path %>
        </p>

    </div>

</div>

app/views/encounters/index.erb
    <div class="flex-container group-paths" >
        <%= link_to "Create an Encounter", new_encounter_path %>
        <%= link_to "All Players", players_path %> 
        <%= link_to "All Monsters", monsters_path %>
        <%= link_to "Logout", "/welcome" %>
    </div>


<h1>Encounters Index</h1>


<div class="grid-container">
    <div class="item1">
        <% @encounters.each do |encounter| %>
            <div>
                <span>
                    The name of this encounter is <%= link_to encounter.name, encounter %>
                </span>
                <span>
                    <%= button_to '⚡️delete', encounter, method: :delete %>
                </span>
            </div>
            
        <% end %>
    </div>
</div>

app/views/encounters/new.html.erb
<h1>Create Encounter</h1>

<%= render 'form_encounters' %>

app/views/encounters/show.html.erb
<h1>Encounter: <%= @encounter.name %> </h1>
<div>
    <h3>Dungeon Master: <%= @encounter.dungeonmaster.name %></h3>
</div>
<p>
    Players: <% @encounter.players.each do |player| %>
        
        <li>
            <span> <strong> Name: </strong> <%= player.name %>  </span>
            <span> <strong> Level: </strong>  <%= player.player_level %>  </span>
            <span> <strong> HP:  </strong> <%= player.player_hp %> </span> 
        </li>
        
    <% end %>
</p>
<p>
    Monsters: <% @encounter.encountermonsters.each do |encountermonster| %>
        
        <li>
        <span>Name: <%= link_to encountermonster.monster.monster_name, encountermonster.monster %> </span>
        <span>CR: <%= encountermonster.monster.challenge_rating %></span>
        <span> <%= button_to "🖕 remove 🖕", encountermonster, method: :delete, :encounter => {:id => @encounter.id} %> </span>
        </li>
    <% end %>
</p>
<p>
    <%= link_to "FIGHT!", encounter_fight_path(@encounter) %>
</p>
<p>
    <%= link_to "Edit this Encounter", edit_encounter_path(@encounter) %>
</p>

<p>
    <%= link_to "Return to Encounter Index", encounters_path %>
</p>