config/routes.rb
Rails.application.routes.draw do
  resources :playerencounters
  resources :encountermonsters
  resources :dungeonmasters
  resources :players
  resources :monsters
  resources :encounters do 
    member do
    get 'fight'
  end
end


  get '/encounters/:id/fight', to: 'encounter#edit', as: "encounter_fight"
  get '/welcome', to: 'login#new'
  post '/login', to: 'login#create'

  root "login#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/player.rb
class Player < ApplicationRecord
    belongs_to :dungeonmaster
    has_many :playerencounters
    has_many :encounters, through: :playerencounters
    has_many :encountermonsters, through: :encounters
    has_many :monsters, through: :encountermonsters

    validates :name, presence: true, uniqueness: true 

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

    before_action :find_player, only: [:show, :edit, :update]

    def index
        @players = @current_dm.players
    end
    
    def new
        @player = Player.new
    end
    
    def show
    end
    
    def create
        @player = Player.new(player_params)
        @player.dungeonmaster_id = session["dungeonmaster_id"]
        @player.save
        redirect_to @player
    end

    
    def edit 
    end
    
    def update
        @player.update(player_params)
        redirect_to players_path
    end
    
    def destroy
        @player.destroy
        redirect_to players_path
    end



    private

    def find_player
        @player = Player.find(params[:id])
    end

    def player_params
        params.require(:player).permit(:name, :player_hp, :player_level, :dungeonmaster_id)
    end


end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form_players.erb
<%= form_for @player do |p| %>

<%= p.label :name %>
<%= p.text_field :name %>

<%= p.label :player_hp %>
<%= p.number_field :player_hp %>

<%= p.label :player_level %>
<%= p.text_field :player_level %>

<%= p.submit %>

<% end %>

app/views/players/_form_players.html.erb
<div class="blindcenter">

    <%= form_for @player do |p| %>

        <%= p.label :name %>
        <%= p.text_field :name %>

        <%= p.label :player_hp %>
        <%= p.select(:player_hp, (1..450))%>


        <%= p.label :player_level %>
        <%= p.select(:player_level, (1..20))%>

        <div id="bigsubmit">
            <%= p.submit %>
        </div>
    <% end %>
</div>

app/views/players/edit.erb
<h1>Edit A Player</h1>

<%= render 'form_players' %>

<button class="ui basic button">
  <i class="icon user"></i>
<%= link_to "DESTROY ME", @player.destroy%>
</button>

app/views/players/index.erb
<div class="flex-container group-paths" >
  <a href = "/players/new"  type="btn btn-primary" class="btn btn-primary">Create a New Player</a>
  <a href='/encounters' type="btn btn-primary" class="btn btn-primary">All Encounters</a>
  <a href='/monsters' type="btn btn-primary" class="btn btn-primary">All Monsters</a>
        
</div>

<h1>Welcome to your Players Index Page</h1>


<h1>My Players</h1>


<% @players.each do |player| %>
<div class="card shadowed" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= player.name %></h5>
    <%= image_tag("king-eric.png", :size => "120x150") %>
    <p>
    <h6 class="card-subtitle mb-2 text-muted">Another Brave Adventurer</h6>
    </p>
    <p class="card-text"><li>HP: <%= player.player_hp %> </li></p>
    <p class="card-text"><li>Level: <%= player.player_level %> </li></p>

    <%= link_to "Details", player, class: "card-link", id: "player_details" %>
  </div>
</div>


<% end %>

app/views/players/new.erb
<h1>Create A Player</h1>

<%= render 'form_players' %>

app/views/players/show.erb
<h1>My name is <%= @player.name  %></h1>

<div class="blindcenter">
<p>HP: <%= @player.player_hp %></p>
<p>Level: <%= @player.player_level %></p>



<%= link_to "Edit My Stats", edit_player_path %> 
<%= link_to "All Players", players_path %>
</div>