config/routes.rb
Rails.application.routes.draw do
  resources :playerencounters
  resources :encountermonsters
  resources :dungeonmasters
  resources :players
  resources :monsters
  resources :encounters do 
    member do
    get 'fight'
  end
end


  get '/encounters/:id/fight', to: 'encounter#edit', as: "encounter_fight"
  get '/welcome', to: 'login#new'
  post '/login', to: 'login#create'

  root "login#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

    def index

    end

    def new
        @dungeonmaster = Dungeonmaster.new
        # redirect_to @dungeonmaster
    end

    def create
        @dungeonmaster = Dungeonmaster.find_by(name: params[:name])
        if @dungeonmaster && @dungeonmaster.authenticate(params[:password])
            session["dungeonmaster_id"] = @dungeonmaster.id 
            redirect_to monsters_path #just a test route for now, should actually take to DM index
        else
            flash[:message] = "incorrect username and/or password."
            redirect_to '/welcome'
        end
    end


end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/login/_form_login.erb
<div id="centered_form"> 


<%= form_tag("/login") do %>
<h1>Login Form</h1>
    <p class="grid-container">
        <div class="item1">
            <%= label_tag :name %>
            <%= text_field_tag :name %>
            <br>
            <br>
            <%= label_tag :password %>
            <%= password_field_tag :password %>
            <br>
            <br>
            <%= submit_tag "Login" %>
        </div>
    </p>

<%end%>



</div>

app/views/login/new.erb
<div>

<h1>Login Form</h1>

<%= form_tag("/login") do %>

    <%= label_tag :username %>
    <%= text_field_tag :username %>
    <br>
    <br>
    <%= label_tag :password %>
    <%= password_field_tag :password %>
<br>
    <br>
    <%= submit_tag "Login" %>

<%end%>

</div>

app/views/login/new.html.erb
<h1>LOGIN</h1>
<h3><%= link_to "Create An Account", new_dungeonmaster_path %></h3>

<%= render 'form_login' %>